name: CI

# 'push' olayına ve 'pull_request' olaylarının main/master branch'ına yapıldığında tetiklenir
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# İş akışları tanımı
jobs:
  build:
    runs-on: ubuntu-latest # Runner'ın çalışacağı işletim sistemi

    steps:
      - uses: actions/checkout@v3 # Repo kodunu checkout eder

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Java sürümü
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests # Maven ile proje inşa edilir
